name: mo-farm-tunnel

services:
  cloudflared:
    image: cloudflare/cloudflared:2025.9.1
    command: ["tunnel", "--no-autoupdate", "--url", "http://nginx:80"]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks: [frontend]

networks:
  frontend:
    external: true
    name: mo-farm-frontend
