worker_processes auto;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  server_tokens off;
  map $http_x_request_id $request_id_value { default $http_x_request_id; "" $request_id; }
  upstream mo_farm_web { server web:4173; }
  upstream mo_farm_api { server api:3000; }
  include /etc/nginx/conf.d/*.conf;
}
